# Generated by Django 3.0.2 on 2020-02-08 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscategory',
            old_name='nema',
            new_name='name',
        ),
    ]
